[package]
name = "elias-fano"
version = "0.2.4"
authors = ["Tom Arrell <tom.arrell@gmail.com>"]
description = "An implementation of Elias-Fano encoding in Rust"
repository = "https://github.com/tomarrell/rust-elias-fano"
readme = "README.md"
license = "MIT"

[dependencies]
fixedbitset = "0.1.9"
